credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$/1fP4UWCYWreDf75GWARM.mRNKzyOcayiogxMFZvdC6yN9nMCO/P2 # To be replaced with hashed password
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$jzXNlcSjLCp5ypwclmTGaOphODTDZfSeh9oL/PFfyl6e37KAjatWy # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: random_signature_key # Must be string
  name: random_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com